// web-vue/app/components/MeetingDrawerHost.vue
<script setup lang="ts">
import { useDrawerStore } from "~/stores/drawer";
import MeetingDrawer from "~/components/MeetingDrawer.vue";

const drawer = useDrawerStore();
</script>

<template>
  <MeetingDrawer v-if="drawer.openMeetingId" :meeting-id="drawer.openMeetingId" @close="drawer.close()" />
</template>

// web/components/MeetingDrawerHost.tsx
"use client";
import { useDrawerStore } from "@/lib/store/drawer";
import { MeetingDrawer } from "./MeetingDrawer";

export function MeetingDrawerHost() {
  const openMeetingId = useDrawerStore((s) => s.openMeetingId);
  const close = useDrawerStore((s) => s.close);
  if (!openMeetingId) return null;
  return <MeetingDrawer meetingId={openMeetingId} onClose={close} />;
}
