// web/components/Modal.tsx
"use client";
import { useEffect } from "react";

export function Modal({
  title, onClose, children,
}: { title: string; onClose: () => void; children: React.ReactNode }) {
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div data-testid="modal-scrim" className="absolute inset-0 bg-black/30 backdrop-blur-sm" onClick={onClose} />
      <div role="dialog" aria-label={title}
        className="relative z-10 w-full max-w-[460px] rounded-lg border border-line bg-bg-elev shadow-pop">
        <div className="flex items-center justify-between border-b border-line px-5 py-3">
          <h2 className="text-[15px] font-semibold text-ink">{title}</h2>
          <button type="button" aria-label="Закрыть" className="text-ink-3 hover:text-ink" onClick={onClose}>✕</button>
        </div>
        <div className="px-5 py-4">{children}</div>
      </div>
    </div>
  );
}

// web-vue/app/components/Modal.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from "vue";

defineProps<{ title: string }>();
const emit = defineEmits<{ close: [] }>();

function onKey(e: KeyboardEvent) {
  if (e.key === "Escape") emit("close");
}
onMounted(() => document.addEventListener("keydown", onKey));
onUnmounted(() => document.removeEventListener("keydown", onKey));
</script>

<template>
  <div class="fixed inset-0 z-50 flex items-center justify-center p-4">
    <div data-testid="modal-scrim" class="absolute inset-0 bg-black/30 backdrop-blur-sm" @click="emit('close')" />
    <div
      role="dialog"
      :aria-label="title"
      class="relative z-10 w-full max-w-[460px] rounded-lg border border-line bg-bg-elev shadow-pop"
    >
      <div class="flex items-center justify-between border-b border-line px-5 py-3">
        <h2 class="text-[15px] font-semibold text-ink">{{ title }}</h2>
        <button type="button" aria-label="Закрыть" class="text-ink-3 hover:text-ink" @click="emit('close')">✕</button>
      </div>
      <div class="px-5 py-4"><slot /></div>
    </div>
  </div>
</template>
