// web/components/NoteBlock.tsx
export function NoteBlock({ label, children }: { label: string; children?: React.ReactNode }) {
  const text = typeof children === "string" ? children.trim() : children;
  if (!text || (Array.isArray(text) && text.length === 0)) return null;
  return (
    <div className="rounded-md border border-line-2 bg-bg-tint p-3">
      <div className="mb-1 text-[11px] font-medium uppercase tracking-wide text-ink-3">{label}</div>
      <div className="text-[13px] text-ink-2">{text}</div>
    </div>
  );
}

// web-vue/app/components/NoteBlock.vue
<script setup lang="ts">
import { Comment, Text, useSlots } from "vue";

defineProps<{ label: string }>();
const slots = useSlots();

// Like React's `children.trim()` check: a blank or missing slot renders nothing.
function isEmpty() {
  const nodes = slots.default?.() ?? [];
  return nodes.every(
    (n) => n.type === Comment || (n.type === Text && String(n.children).trim() === ""),
  );
}
</script>

<template>
  <div v-if="!isEmpty()" class="rounded-md border border-line-2 bg-bg-tint p-3">
    <div class="mb-1 text-[11px] font-medium uppercase tracking-wide text-ink-3">{{ label }}</div>
    <div class="text-[13px] text-ink-2"><slot /></div>
  </div>
</template>
