// web-vue/app/components/goals/CompetencyEditModal.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import Modal from "~/components/Modal.vue";
import CompetencyForm, { type CompetencyValues } from "~/components/goals/CompetencyForm.vue";
import { useCreateCompetency, useUpdateCompetency, useDeleteCompetency } from "~/lib/query/goals";
import type { Competency } from "~/lib/query/profile";

const props = defineProps<{ memberId: string; competency?: Competency }>();
const emit = defineEmits<{ close: [] }>();

const create = useCreateCompetency(() => props.memberId);
const update = useUpdateCompetency(() => props.memberId);
const del = useDeleteCompetency(() => props.memberId);
const error = ref<string | null>(null);
const pending = computed(() => create.isPending.value || update.isPending.value || del.isPending.value);

const onClose = () => emit("close");

function submit(v: CompetencyValues) {
  error.value = null;
  const onError = () => (error.value = "Не удалось сохранить");
  if (props.competency) update.mutate({ id: props.competency.id, body: v }, { onSuccess: onClose, onError });
  else create.mutate({ member_id: props.memberId, ...v }, { onSuccess: onClose, onError });
}
function remove() {
  if (props.competency && confirm("Удалить компетенцию?"))
    del.mutate(props.competency.id, { onSuccess: onClose, onError: () => (error.value = "Не удалось удалить") });
}
</script>

<template>
  <Modal :title="competency ? 'Изменить компетенцию' : 'Новая компетенция'" @close="onClose">
    <CompetencyForm :initial="competency" :on-delete="competency ? remove : undefined" :pending="pending" :error="error" @submit="submit" />
  </Modal>
</template>

// web/components/goals/CompetencyEditModal.tsx
"use client";
import { useState } from "react";
import { Modal } from "@/components/Modal";
import { CompetencyForm, type CompetencyValues } from "./CompetencyForm";
import { useCreateCompetency, useUpdateCompetency, useDeleteCompetency } from "@/lib/query/goals";
import type { Competency } from "@/lib/query/profile";

export function CompetencyEditModal({ memberId, competency, onClose }: { memberId: string; competency?: Competency; onClose: () => void }) {
  const create = useCreateCompetency(memberId);
  const update = useUpdateCompetency(memberId);
  const del = useDeleteCompetency(memberId);
  const [error, setError] = useState<string | null>(null);
  const pending = create.isPending || update.isPending || del.isPending;

  function submit(v: CompetencyValues) {
    setError(null);
    const onError = () => setError("Не удалось сохранить");
    if (competency) update.mutate({ id: competency.id, body: v }, { onSuccess: onClose, onError });
    else create.mutate({ member_id: memberId, ...v }, { onSuccess: onClose, onError });
  }
  function remove() {
    if (competency && confirm("Удалить компетенцию?"))
      del.mutate(competency.id, { onSuccess: onClose, onError: () => setError("Не удалось удалить") });
  }

  return (
    <Modal title={competency ? "Изменить компетенцию" : "Новая компетенция"} onClose={onClose}>
      <CompetencyForm initial={competency} onSubmit={submit} onDelete={competency ? remove : undefined} pending={pending} error={error} />
    </Modal>
  );
}
