// web-vue/app/components/goals/DevItemEditModal.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import Modal from "~/components/Modal.vue";
import DevItemForm, { type DevItemValues } from "~/components/goals/DevItemForm.vue";
import { useCreateDevItem, useUpdateDevItem, useDeleteDevItem } from "~/lib/query/goals";
import type { DevItem } from "~/lib/query/profile";

const props = defineProps<{ memberId: string; item?: DevItem }>();
const emit = defineEmits<{ close: [] }>();

const create = useCreateDevItem(() => props.memberId);
const update = useUpdateDevItem(() => props.memberId);
const del = useDeleteDevItem(() => props.memberId);
const error = ref<string | null>(null);
const pending = computed(() => create.isPending.value || update.isPending.value || del.isPending.value);

const onClose = () => emit("close");

function submit(v: DevItemValues) {
  error.value = null;
  const onError = () => (error.value = "Не удалось сохранить");
  if (props.item) update.mutate({ id: props.item.id, body: v }, { onSuccess: onClose, onError });
  else create.mutate({ member_id: props.memberId, ...v }, { onSuccess: onClose, onError });
}
function remove() {
  if (props.item && confirm("Удалить пункт?"))
    del.mutate(props.item.id, { onSuccess: onClose, onError: () => (error.value = "Не удалось удалить") });
}
</script>

<template>
  <Modal :title="item ? 'Изменить пункт' : 'Новый пункт развития'" @close="onClose">
    <DevItemForm :initial="item" :on-delete="item ? remove : undefined" :pending="pending" :error="error" @submit="submit" />
  </Modal>
</template>

// web/components/goals/DevItemEditModal.tsx
"use client";
import { useState } from "react";
import { Modal } from "@/components/Modal";
import { DevItemForm, type DevItemValues } from "./DevItemForm";
import { useCreateDevItem, useUpdateDevItem, useDeleteDevItem } from "@/lib/query/goals";
import type { DevItem } from "@/lib/query/profile";

export function DevItemEditModal({ memberId, item, onClose }: { memberId: string; item?: DevItem; onClose: () => void }) {
  const create = useCreateDevItem(memberId);
  const update = useUpdateDevItem(memberId);
  const del = useDeleteDevItem(memberId);
  const [error, setError] = useState<string | null>(null);
  const pending = create.isPending || update.isPending || del.isPending;

  function submit(v: DevItemValues) {
    setError(null);
    const onError = () => setError("Не удалось сохранить");
    if (item) update.mutate({ id: item.id, body: v }, { onSuccess: onClose, onError });
    else create.mutate({ member_id: memberId, ...v }, { onSuccess: onClose, onError });
  }
  function remove() {
    if (item && confirm("Удалить пункт?"))
      del.mutate(item.id, { onSuccess: onClose, onError: () => setError("Не удалось удалить") });
  }

  return (
    <Modal title={item ? "Изменить пункт" : "Новый пункт развития"} onClose={onClose}>
      <DevItemForm initial={item} onSubmit={submit} onDelete={item ? remove : undefined} pending={pending} error={error} />
    </Modal>
  );
}
