// web/components/goals/CompetencyForm.tsx
"use client";
import { useState } from "react";
import { Field, FormFooter } from "./OkrForm";
import type { Competency } from "@/lib/query/profile";

export type CompetencyValues = { label: string; score: number };

const inp = "w-full rounded-md border border-line bg-bg-elev px-2 py-1.5 text-[13px] text-ink";

export function CompetencyForm({
  initial, onSubmit, onDelete, pending, error,
}: {
  initial?: Competency;
  onSubmit: (v: CompetencyValues) => void;
  onDelete?: () => void;
  pending: boolean;
  error: string | null;
}) {
  const [label, setLabel] = useState(initial?.label ?? "");
  const [score, setScore] = useState(initial?.score ?? 5);

  function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!label.trim()) return;
    onSubmit({ label: label.trim(), score: Math.max(0, Math.min(10, score)) });
  }

  return (
    <form onSubmit={submit} className="space-y-3 text-[13px]">
      <Field label="Компетенция"><input className={inp} value={label} onChange={(e) => setLabel(e.target.value)} /></Field>
      <Field label="Оценка">
        <input type="number" min={0} max={10} className={inp} value={score}
          onChange={(e) => setScore(Number(e.target.value))} />
      </Field>
      <FormFooter pending={pending} error={error} onDelete={onDelete} />
    </form>
  );
}

// web-vue/app/components/goals/CompetencyForm.vue
<script lang="ts">
export type CompetencyValues = { label: string; score: number };
</script>

<script setup lang="ts">
import { ref } from "vue";
import Field from "~/components/goals/Field.vue";
import FormFooter from "~/components/goals/FormFooter.vue";
import type { Competency } from "~/lib/query/profile";

const inp = "w-full rounded-md border border-line bg-bg-elev px-2 py-1.5 text-[13px] text-ink";

const props = defineProps<{ initial?: Competency; onDelete?: () => void; pending: boolean; error: string | null }>();
const emit = defineEmits<{ submit: [v: CompetencyValues] }>();

const label = ref(props.initial?.label ?? "");
const score = ref(props.initial?.score ?? 5);

function submit() {
  if (!label.value.trim()) return;
  emit("submit", { label: label.value.trim(), score: Math.max(0, Math.min(10, score.value)) });
}
</script>

<template>
  <form class="space-y-3 text-[13px]" @submit.prevent="submit">
    <Field label="Компетенция"><input v-model="label" :class="inp" /></Field>
    <Field label="Оценка">
      <input
        type="number" min="0" max="10" :class="inp" :value="score"
        @input="score = Number(($event.target as HTMLInputElement).value)"
      />
    </Field>
    <FormFooter :pending="pending" :error="error" :on-delete="onDelete" />
  </form>
</template>
