// web-vue/app/pages/calendar.vue
<script setup lang="ts">
import NoAccess from "~/components/NoAccess.vue";
import CalendarClient from "~/components/calendar/CalendarClient.vue";
import { hasPermission } from "~/lib/permissions";

const user = useSessionUser(); // middleware already guaranteed non-null
const canManage = computed(() => !user.value || hasPermission(user.value, "manage_team"));
</script>

<template>
  <CalendarClient v-if="canManage" :team-id="user?.teamId ?? null" />
  <NoAccess v-else />
</template>

// web/app/(app)/calendar/page.tsx
import { getSessionUser, hasPermission } from "@/lib/auth";
import { NoAccess } from "@/components/NoAccess";
import { CalendarClient } from "@/components/calendar/CalendarClient";

export default async function CalendarPage() {
  const user = await getSessionUser(); // layout guarantees non-null
  if (user && !hasPermission(user, "manage_team")) return <NoAccess />;
  return <CalendarClient teamId={user?.teamId ?? null} />;
}
